### ISSUE TITLE
Quality of compression 

### ISSUE THREAD

**Issue by TheGreatRambler** [PixelyIon/ZRA#1]
Could you make a benchmark or something to see how this compares to other compression algorithms? I find this very interesting

**Comment by PixelyIon** [comment]
Sorry on being late to this, we're a bit busy with some other projects at the moment. @Xpl0itR is working on Python bindings, we'll work on adding benchmarks besides that. 
Thanks for you interest in the project :)

**Comment by PixelyIon** [comment]
Sorry but due to never actually finding time to work on the project again, it's pretty much in maintenance mode. I'm open to any PRs but this isn't something I'm actively pursuing.
