### ISSUE TITLE
Overflow in CalculateHash

### ISSUE THREAD

**Issue by tauffe** [PixelyIon/ZRA#3]
Hello great library. Running with sanitizer I had some complain about overflow in CalculateHash.
I think it is because the pointer and size passed are  double counting sizeof(FixedHeader)

Substracting it in return CRC:;Calculate(rest, headerSize - sizeof(FixedHeader) does the trick.

Rgds

**Comment by PixelyIon** [comment]
Hi, this library is more or less in maintenance mode since we never actually got to using it for projects we wanted to. If there's any issues feel free to open a PR and I'll merge it.

**Comment by tauffe** [comment]
Hello yes I will. Thanks

**Comment by tauffe** [comment]
Actually I'll need to create a remote branch to push the fixes.Rgds
